title: "قاموس الإرهاق الرقمي"
description: "مرجع شامل لمصطلحات الإرهاق الرقمي وتخمة المعلومات."
baseurl: ""
url: "https://adham23233.github.io"

# Plugins (اختياري)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
